// <auto-generated />
using System;
using System.Net;
using Maquinaria.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maquinaria.Infraestructura.Migraciones.Empresa
{
    [DbContext(typeof(ContextoEmpresa))]
    [Migration("20260821191557_EmpresaInicial")]
    partial class EmpresaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.Permiso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modulo");

                    b.HasKey("Id")
                        .HasName("pk_permiso");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("permiso_clave_unica");

                    b.HasIndex("Modulo")
                        .HasDatabaseName("ix_permiso_modulo");

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AccesoTotal")
                        .HasColumnType("boolean")
                        .HasColumnName("acceso_total");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_sistema");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_rol");

                    b.HasIndex("AccesoTotal")
                        .IsUnique()
                        .HasDatabaseName("rol_acceso_total_unico")
                        .HasFilter("acceso_total");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("rol_codigo_unico");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.RolPermiso", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<Guid>("PermisoId")
                        .HasColumnType("uuid")
                        .HasColumnName("permiso_id");

                    b.HasKey("RolId", "PermisoId")
                        .HasName("pk_rol_permiso");

                    b.HasIndex("PermisoId")
                        .HasDatabaseName("ix_rol_permiso_permiso_id");

                    b.ToTable("rol_permiso", (string)null);
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.SesionRefresh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgenteUsuario")
                        .HasColumnType("text")
                        .HasColumnName("agente_usuario");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_token");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<Guid?>("ReemplazadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("reemplazado_por_id");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sesion_refresh");

                    b.HasIndex("HashToken")
                        .IsUnique()
                        .HasDatabaseName("sesion_refresh_hash_unico");

                    b.HasIndex("ReemplazadoPorId")
                        .HasDatabaseName("ix_sesion_refresh_reemplazado_por_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sesion_usuario_activa")
                        .HasFilter("revocado_en IS NULL");

                    b.ToTable("sesion_refresh", null, t =>
                        {
                            t.HasCheckConstraint("sesion_refresh_vigencia", "expira_en > creado_en");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.TokenAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creado_por_id");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_token");

                    b.Property<DateTime?>("InvalidadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidado_en");

                    b.Property<short>("Proposito")
                        .HasColumnType("smallint")
                        .HasColumnName("proposito");

                    b.Property<DateTime?>("UsadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_token_acceso");

                    b.HasIndex("CreadoPorId")
                        .HasDatabaseName("ix_token_acceso_creado_por_id");

                    b.HasIndex("HashToken")
                        .IsUnique()
                        .HasDatabaseName("token_acceso_hash_unico");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_token_acceso_pendiente")
                        .HasFilter("usado_en IS NULL AND invalidado_en IS NULL");

                    b.ToTable("token_acceso", null, t =>
                        {
                            t.HasCheckConstraint("token_acceso_proposito", "proposito BETWEEN 1 AND 2");

                            t.HasCheckConstraint("token_acceso_vigencia", "expira_en > creado_en");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellidos")
                        .HasColumnType("text")
                        .HasColumnName("apellidos");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("DebeCambiarContrasena")
                        .HasColumnType("boolean")
                        .HasColumnName("debe_cambiar_contrasena");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<string>("HashContrasena")
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<DateTime?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_en");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("usuario_correo_unico");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_usuario_estado");

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("usuario_estado", "estado BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId", "RolId")
                        .HasName("pk_usuario_rol");

                    b.HasIndex("RolId")
                        .HasDatabaseName("ix_usuario_rol_rol_id");

                    b.ToTable("usuario_rol", (string)null);
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.RolPermiso", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Seguridad.Permiso", "Permiso")
                        .WithMany("Roles")
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rol_permiso_permiso");

                    b.HasOne("Maquinaria.Dominio.Seguridad.Rol", "Rol")
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_permiso_rol");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.SesionRefresh", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Seguridad.SesionRefresh", "ReemplazadoPor")
                        .WithMany()
                        .HasForeignKey("ReemplazadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sesion_refresh_reemplazo");

                    b.HasOne("Maquinaria.Dominio.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sesion_refresh_usuario");

                    b.Navigation("ReemplazadoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.TokenAcceso", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Seguridad.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_token_acceso_creado_por");

                    b.HasOne("Maquinaria.Dominio.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_acceso_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Seguridad.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_rol");

                    b.HasOne("Maquinaria.Dominio.Seguridad.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.Permiso", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.Rol", b =>
                {
                    b.Navigation("Permisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Seguridad.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
