// <auto-generated />
using System;
using Maquinaria.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maquinaria.Infraestructura.Migraciones.Central
{
    [DbContext(typeof(ContextoCentral))]
    [Migration("20260821032808_CentralInicial")]
    partial class CentralInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MXN")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("precio_mensual");

                    b.HasKey("Id")
                        .HasName("pk_plan");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("plan_codigo_unico");

                    b.ToTable("plan", null, t =>
                        {
                            t.HasCheckConstraint("plan_moneda_valida", "length(moneda) = 3");

                            t.HasCheckConstraint("plan_precio_valido", "precio_mensual >= 0");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.PlanLimite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<int>("Valor")
                        .HasColumnType("integer")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_plan_limite");

                    b.HasIndex("PlanId", "Clave")
                        .IsUnique()
                        .HasDatabaseName("plan_limite_unico");

                    b.ToTable("plan_limite", null, t =>
                        {
                            t.HasCheckConstraint("plan_limite_valor", "valor >= -1");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Suscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_suscripcion");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_suscripcion_plan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_suscripcion_tenant");

                    b.ToTable("suscripcion", null, t =>
                        {
                            t.HasCheckConstraint("suscripcion_estado", "estado BETWEEN 1 AND 4");

                            t.HasCheckConstraint("suscripcion_periodo_valido", "fin IS NULL OR fin > inicio");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("CorreoContacto")
                        .HasColumnType("text")
                        .HasColumnName("correo_contacto");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("DiaPago")
                        .HasColumnType("smallint")
                        .HasColumnName("dia_pago");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<short>("EstadoAprovisionamiento")
                        .HasColumnType("smallint")
                        .HasColumnName("estado_aprovisionamiento");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MXN")
                        .HasColumnName("moneda");

                    b.Property<string>("NombreBd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_bd");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rfc")
                        .HasColumnType("text")
                        .HasColumnName("rfc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("VersionEsquema")
                        .HasColumnType("text")
                        .HasColumnName("version_esquema");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("America/Mexico_City")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_tenant_estado")
                        .HasFilter("eliminado_en IS NULL");

                    b.HasIndex("NombreBd")
                        .IsUnique()
                        .HasDatabaseName("tenant_bd_unica");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("tenant_slug_unico");

                    b.ToTable("tenant", null, t =>
                        {
                            t.HasCheckConstraint("tenant_aprovisionamiento", "estado_aprovisionamiento BETWEEN 1 AND 4");

                            t.HasCheckConstraint("tenant_bd_formato", "nombre_bd ~ '^[a-z][a-z0-9_]{2,62}$'");

                            t.HasCheckConstraint("tenant_dia_pago", "dia_pago IS NULL OR dia_pago BETWEEN 1 AND 31");

                            t.HasCheckConstraint("tenant_estado", "estado BETWEEN 1 AND 4");

                            t.HasCheckConstraint("tenant_moneda_valida", "length(moneda) = 3");

                            t.HasCheckConstraint("tenant_slug_formato", "slug ~ '^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$'");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.UsuarioPlataforma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_en");

                    b.HasKey("Id")
                        .HasName("pk_usuario_plataforma");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("usuario_plataforma_correo_unico");

                    b.ToTable("usuario_plataforma", (string)null);
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.PlanLimite", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Plataforma.Plan", "Plan")
                        .WithMany("Limites")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_limite_plan");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Suscripcion", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Plataforma.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_plan");

                    b.HasOne("Maquinaria.Dominio.Plataforma.Tenant", "Tenant")
                        .WithMany("Suscripciones")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_tenant");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Plan", b =>
                {
                    b.Navigation("Limites");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Tenant", b =>
                {
                    b.Navigation("Suscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
