// <auto-generated />
using System;
using System.Net;
using Maquinaria.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maquinaria.Infraestructura.Migraciones.Central
{
    [DbContext(typeof(ContextoCentral))]
    [Migration("20260821192957_CentralAuditoria")]
    partial class CentralAuditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("numero");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_modulo");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("modulo_clave_unica");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("modulo_numero_unico");

                    b.ToTable("modulo", null, t =>
                        {
                            t.HasCheckConstraint("modulo_numero_rango", "numero BETWEEN 1 AND 99");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MXN")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("precio_mensual");

                    b.HasKey("Id")
                        .HasName("pk_plan");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("plan_codigo_unico");

                    b.ToTable("plan", null, t =>
                        {
                            t.HasCheckConstraint("plan_moneda_valida", "length(moneda) = 3");

                            t.HasCheckConstraint("plan_precio_valido", "precio_mensual >= 0");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.PlanModulo", b =>
                {
                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_id");

                    b.HasKey("PlanId", "ModuloId")
                        .HasName("pk_plan_modulo");

                    b.HasIndex("ModuloId")
                        .HasDatabaseName("ix_plan_modulo_modulo_id");

                    b.ToTable("plan_modulo", (string)null);
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Suscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fin");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_suscripcion");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_suscripcion_plan_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_suscripcion_tenant");

                    b.ToTable("suscripcion", null, t =>
                        {
                            t.HasCheckConstraint("suscripcion_estado", "estado BETWEEN 1 AND 4");

                            t.HasCheckConstraint("suscripcion_periodo_valido", "fin IS NULL OR fin > inicio");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("CorreoContacto")
                        .HasColumnType("text")
                        .HasColumnName("correo_contacto");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("DiaPago")
                        .HasColumnType("smallint")
                        .HasColumnName("dia_pago");

                    b.Property<DateTime?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_en");

                    b.Property<short>("Estado")
                        .HasColumnType("smallint")
                        .HasColumnName("estado");

                    b.Property<short>("EstadoAprovisionamiento")
                        .HasColumnType("smallint")
                        .HasColumnName("estado_aprovisionamiento");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("MXN")
                        .HasColumnName("moneda");

                    b.Property<string>("NombreBd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_bd");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("text")
                        .HasColumnName("nombre_comercial");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("Rfc")
                        .HasColumnType("text")
                        .HasColumnName("rfc");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("VersionEsquema")
                        .HasColumnType("text")
                        .HasColumnName("version_esquema");

                    b.Property<string>("ZonaHoraria")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("America/Mexico_City")
                        .HasColumnName("zona_horaria");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_tenant_estado")
                        .HasFilter("eliminado_en IS NULL");

                    b.HasIndex("NombreBd")
                        .IsUnique()
                        .HasDatabaseName("tenant_bd_unica");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("tenant_slug_unico");

                    b.ToTable("tenant", null, t =>
                        {
                            t.HasCheckConstraint("tenant_aprovisionamiento", "estado_aprovisionamiento BETWEEN 1 AND 4");

                            t.HasCheckConstraint("tenant_bd_formato", "nombre_bd ~ '^[a-z][a-z0-9_]{2,62}$'");

                            t.HasCheckConstraint("tenant_dia_pago", "dia_pago IS NULL OR dia_pago BETWEEN 1 AND 31");

                            t.HasCheckConstraint("tenant_estado", "estado BETWEEN 1 AND 4");

                            t.HasCheckConstraint("tenant_moneda_valida", "length(moneda) = 3");

                            t.HasCheckConstraint("tenant_slug_formato", "slug ~ '^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$'");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.TenantLimite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TipoLimiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("tipo_limite_id");

                    b.Property<int>("Valor")
                        .HasColumnType("integer")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_tenant_limite");

                    b.HasIndex("TipoLimiteId")
                        .HasDatabaseName("ix_tenant_limite_tipo_limite_id");

                    b.HasIndex("TenantId", "TipoLimiteId")
                        .IsUnique()
                        .HasDatabaseName("tenant_limite_unico");

                    b.ToTable("tenant_limite", null, t =>
                        {
                            t.HasCheckConstraint("tenant_limite_valor", "valor >= -1");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.TipoLimite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unidad");

                    b.Property<int>("ValorDefecto")
                        .HasColumnType("integer")
                        .HasColumnName("valor_defecto");

                    b.HasKey("Id")
                        .HasName("pk_tipo_limite");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("tipo_limite_clave_unica");

                    b.ToTable("tipo_limite", null, t =>
                        {
                            t.HasCheckConstraint("tipo_limite_defecto", "valor_defecto >= -1");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_en");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("usuario_correo_unico");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Maquinaria.Dominio.Trazabilidad.Auditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<short>("Accion")
                        .HasColumnType("smallint")
                        .HasColumnName("accion");

                    b.Property<Guid>("CorrelacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlacion_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidad_id");

                    b.Property<DateTime>("FechaUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origen");

                    b.PrimitiveCollection<string[]>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("roles");

                    b.Property<string>("UsuarioCorreo")
                        .HasColumnType("text")
                        .HasColumnName("usuario_correo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_anteriores");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_nuevos");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("CorrelacionId")
                        .HasDatabaseName("ix_auditoria_correlacion");

                    b.HasIndex("FechaUtc")
                        .IsDescending()
                        .HasDatabaseName("ix_auditoria_fecha");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_auditoria_entidad");

                    b.HasIndex("UsuarioId", "FechaUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_auditoria_usuario");

                    b.ToTable("auditoria", null, t =>
                        {
                            t.HasCheckConstraint("auditoria_accion", "accion BETWEEN 1 AND 8");
                        });
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.PlanModulo", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Plataforma.Modulo", "Modulo")
                        .WithMany("Planes")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_modulo_modulo");

                    b.HasOne("Maquinaria.Dominio.Plataforma.Plan", "Plan")
                        .WithMany("Modulos")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_modulo_plan");

                    b.Navigation("Modulo");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Suscripcion", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Plataforma.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_plan");

                    b.HasOne("Maquinaria.Dominio.Plataforma.Tenant", "Tenant")
                        .WithMany("Suscripciones")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripcion_tenant");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.TenantLimite", b =>
                {
                    b.HasOne("Maquinaria.Dominio.Plataforma.Tenant", "Tenant")
                        .WithMany("Limites")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_limite_tenant");

                    b.HasOne("Maquinaria.Dominio.Plataforma.TipoLimite", "TipoLimite")
                        .WithMany()
                        .HasForeignKey("TipoLimiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_limite_tipo");

                    b.Navigation("Tenant");

                    b.Navigation("TipoLimite");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Modulo", b =>
                {
                    b.Navigation("Planes");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Plan", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("Maquinaria.Dominio.Plataforma.Tenant", b =>
                {
                    b.Navigation("Limites");

                    b.Navigation("Suscripciones");
                });
#pragma warning restore 612, 618
        }
    }
}
